package:
  format-version: "1.0.0"
  name: "mplab_dvrt"
  type: "api"
  status: "production"
  required: true
  version: "v3.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.19.1"
    

